version: '2'
services:
  nginx:
    image: nginx:alpine
    working_dir: /application
    volumes:
      # - ./code/:/application/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites/enabled:/etc/nginx/sites-enabled
    ports:
     - "8080:80"
    links:
      - php-fpm-56:php-fpm
    networks:
      static-network:
        ipv4_address: 172.168.1.55

  # php-fpm-71:
  #   build: build/php-fpm-7.1
  #   working_dir: /application
  #   volumes:
  #     - ./code/:/application/
  #     - ./conf/php/php.ini:/opt/bitnami/php/etc/conf.d/99-overrides.ini
  #   # extra_hosts:
  #     # - "idp.test:172.168.1.55"
  #   links:
  #     - mysql:mysql
  #     # - redis:redis
  #     - mailhog:mailhog
  #     # - memcached:memcached
  #   networks:
  #     static-network:
  #       ipv4_address: 172.168.1.33

  php-fpm-56:
    image: bitnami/php-fpm:5.6
    # build: build/php-fpm-5.6
    volumes:
      # - ./code/:/application/
      - ./conf/php/php56.ini:/opt/bitnami/php/etc/conf.d/99-overrides.ini
    links:
      - mysql:mysql
      # - redis:redis
      - mailhog:mailhog
      # - memcached:memcached
    extra_hosts:
      - "vltp.dockerhost:172.168.1.55"
    networks:
      static-network:
        ipv4_address: 172.168.1.34

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8026:8025"
      - "1026:1025"
    networks:
      - static-network
      
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
    networks:
      - static-network

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - static-network

  # memcached:
  #   image: memcached:1.4
  #   ports:
  #     - "11211:11211"
  #   networks:
  #     - static-network

  # elasticsearch:
  #   image: elasticsearch:2.3
  #   ports:
  #     - "9202:9200"
  #     - "9302:9300"
  #   volumes:
  #     - ./conf/elasticsearch:/usr/share/elasticsearch/config

  # beanstalkd:
  #   image: schickling/beanstalkd
  #   ports:
  #     - "11300:11300"

  # solr:
  #   image: solr:6.6
  #   ports:
  #     - "8983:8983"
  #   volumes:
  #     - ./data/solr:/opt/solr/server/solr/mycores
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - gls_activity
  #   environment:
  #     SOLR_HEAP: 1024m

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.168.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 172.168.1.0/24